<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit25dc1f3491bbf1669de2cefedc9f737b
{
    public static $prefixLengthsPsr4 = array (
        'G' => 
        array (
            'Grafika\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Grafika\\' => 
        array (
            0 => __DIR__ . '/..' . '/kosinix/grafika/src/Grafika',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit25dc1f3491bbf1669de2cefedc9f737b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit25dc1f3491bbf1669de2cefedc9f737b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
