<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'fd419dbaef6da3b0a9513930c6ff3624' => $vendorDir . '/wapmorgan/unified-archive/src/function.gzip_stat.php',
    '9e1b3d8b1d64afff01a1869b5f98e4e3' => $vendorDir . '/wapmorgan/unified-archive/src/REGISTER_LZW_STREAM_WRAPPER.php',
);
