<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit24d7bf014d06ead89f95c8d635e83498
{
    public static $files = array (
        'fd419dbaef6da3b0a9513930c6ff3624' => __DIR__ . '/..' . '/wapmorgan/unified-archive/src/function.gzip_stat.php',
        '9e1b3d8b1d64afff01a1869b5f98e4e3' => __DIR__ . '/..' . '/wapmorgan/unified-archive/src/REGISTER_LZW_STREAM_WRAPPER.php',
    );

    public static $prefixLengthsPsr4 = array (
        'w' => 
        array (
            'wapmorgan\\UnifiedArchive\\' => 25,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'wapmorgan\\UnifiedArchive\\' => 
        array (
            0 => __DIR__ . '/..' . '/wapmorgan/unified-archive/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit24d7bf014d06ead89f95c8d635e83498::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit24d7bf014d06ead89f95c8d635e83498::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
