<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Workerman\\' => array($vendorDir . '/workerman/workerman-for-win'),
    'PHPSocketIO\\' => array($vendorDir . '/workerman/phpsocket.io-for-win/src'),
);
