<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf2c4967e52c6965c413bb35db3c2aa7b
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'ColorThief\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ColorThief\\' => 
        array (
            0 => __DIR__ . '/..' . '/ksubileau/color-thief-php/lib/ColorThief',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf2c4967e52c6965c413bb35db3c2aa7b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf2c4967e52c6965c413bb35db3c2aa7b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
